CA_ADMIN_NAME=
CA_ADMIN_PASSWORD=

ROOT_MSP=
ROOT_NUMBER=
ROOT_PASSWORD=

JWE_SECRET=

FABRIC_PEM_PATH=

export CA_ADMIN_NAME CA_ADMIN_PASSWORD ROOT_MSP ROOT_NUMBER ROOT_PASSWORD JWE_SECRET FABRIC_PEM_PATH
